apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-dev
  annotations:
    secrets-webhook.security.bank-vaults.io/provider: "vault"
    secrets-webhook.security.bank-vaults.io/vault-addr: "http://localhost:8200"
data:
  plain: vault:secret/data/database/test#username
  template: user=${vault:secret/data/database/test#username}
